import { TypeStore, TypeStoreClass, TypeStoreFunction, TypeStoreDestroyFunction, TypeStoreSubscribeFunction, TypeStoreOnSubscribeFunction, TypeStoreOnDestroyFunction, TypeStoreOnUpdateFunction, TypeStoreOnChangeFunction } from '@wareset/store';
export { TypeStore, TypeStoreClass, TypeStoreFunction, TypeStoreDestroyFunction, TypeStoreSubscribeFunction, TypeStoreOnSubscribeFunction, TypeStoreOnDestroyFunction, TypeStoreOnUpdateFunction, TypeStoreOnChangeFunction };
import { Store, isStore, store as storeModule, storeDestroy as storeModuleDestroy, storeSubscribe as storeModuleSubscribe, storeOnSubscribe as storeModuleOnSubscribe, storeOnDestroy as storeModuleOnDestroy, storeOnUpdate as storeModuleOnUpdate, storeOnChange as storeModuleOnChange } from '@wareset/store';
export { Store, isStore, storeModule, storeModuleDestroy, storeModuleSubscribe };
export { storeModuleOnSubscribe, storeModuleOnDestroy, storeModuleOnUpdate, storeModuleOnChange };
import { TypeRease } from '.';
export declare const storeReadonlyfy: <V, T extends TypeStore<V>>(store: T) => T;
export declare const storeProxyFactory: (store: TypeStoreFunction) => (...a: any[]) => TypeStore<any>;
export declare type TypeStoreProxyFunction = ReturnType<typeof storeProxyFactory>;
export declare const storeModuleProxy: (...a: any[]) => TypeStore<any>;
export declare const store: (rease?: TypeRease | null) => TypeStoreFunction;
export declare const storeProxy: (rease?: TypeRease | null) => TypeStoreProxyFunction;
export declare const storeDestroy: (rease?: TypeRease | null) => TypeStoreDestroyFunction;
export declare const storeSubscribe: (rease?: TypeRease | null) => TypeStoreSubscribeFunction;
export declare const storeOnSubscribe: (rease?: TypeRease | null) => TypeStoreOnSubscribeFunction;
export declare const storeOnDestroy: (rease?: TypeRease | null) => TypeStoreOnDestroyFunction;
export declare const storeOnUpdate: (rease?: TypeRease | null) => TypeStoreOnUpdateFunction;
export declare const storeOnChange: (rease?: TypeRease | null) => TypeStoreOnChangeFunction;
export declare const getStoreValue: <T>(value: T | TypeStore<T>) => T;
export declare const storefy: (rease?: TypeRease | null) => <T>(value: T | TypeStore<T>, instance?: boolean) => TypeStore<T>;
